const apiCollection: Array<any> = [
  { yek: "internal_notes", xmlYek: "internal_notes", api: "", description: "" },
  {
    yek: "get_action_taken_response",
    xmlYek: "get_action_taken_response",
    api: "",
    description: "",
  },
  {
    yek: "save_action_taken_response",
    xmlYek: "save_action_taken_response",
    api: "",
    description: "",
  },
  {
    yek: "delete_action_taken_response",
    xmlYek: "delete_action_taken_response",
    api: "",
    description: "",
  },
  {
    yek: "get_approval_details",
    xmlYek: "get_approval_details",
    api: "",
    description: "",
  },
  {
    yek: "action-taken-report",
    xmlYek: "action-taken-report",
    api: "",
    description: "",
  },
  {
    yek: "action-report-data-delete",
    xmlYek: "action-report-data-delete",
    api: "",
    description: "",
  },
  {
    yek: "action-report-data-save",
    xmlYek: "action-report-data-save",
    api: "",
    description: "",
  },
  {
    yek: "Department_Combo",
    xmlYek: "Department_Combo",
    api: "",
    description: "",
  },
  { yek: "User_Xml_Data", xmlYek: "User_Xml_Data", api: "", description: "" },
  { yek: "selectAtrNum", xmlYek: "selectAtrNum", api: "", description: "" },
  {
    yek: "Create_Internal_Note_Report",
    xmlYek: "Create_Internal_Note_Report",
    api: "",
    description: "",
  },
  {
    yek: "action_point_xmldata",
    xmlYek: "action_point_xmldata",
    api: "",
    description: "",
  },
  {
    yek: "get_unit_master_details",
    xmlYek: "get_unit_master_details",
    api: "",
    description: "",
  },
  {
    yek: "get_purpose_master_details",
    xmlYek: "get_purpose_master_details",
    api: "",
    description: "",
  },
  {
    yek: "get_currency_master_details",
    xmlYek: "get_currency_master_details",
    api: "",
    description: "",
  },
  {
    yek: "get_currency_unit_master_details",
    xmlYek: "get_currency_unit_master_details",
    api: "",
    description: "",
  },
  {
    yek: "get_sub_dept_master_details",
    xmlYek: "get_sub_dept_master_details",
    api: "",
    description: "",
  },
  {
    yek: "get_dept_master_details",
    xmlYek: "get_dept_master_details",
    api: "",
    description: "",
  },
  {
    yek: "validate_login_credentials",
    xmlYek: "validate_login_credentials",
    api: "",
    description: "",
  },
  {
    yek: "get_basicmaster_detailsByName",
    xmlYek: "get_basicmaster_detailsByName",
    api: "",
    description: "",
  },
  { yek: "save_Workflow", xmlYek: "save_Workflow", api: "", description: "" },
  {
    yek: "get_approvaltransactions",
    xmlYek: "get_approvaltransactions",
    api: "",
    description: "",
  },
  {
    yek: "save_internal_note_master_details",
    xmlYek: "save_internal_note_master_details",
    api: "",
    description: "",
  },
  {
    yek: "get_department_ref_no",
    xmlYek: "get_department_ref_no",
    api: "",
    description: "",
  },
  {
    yek: "save_internal_note_master_details",
    xmlYek: "save_internal_note_master_details",
    api: "",
    description: "",
  },
  {
    yek: "get_department_ref_no",
    xmlYek: "get_department_ref_no",
    api: "",
    description: "",
  },
  {
    yek: "remainder_frequency",
    xmlYek: "remainder_frequency",
    api: "",
    description: "",
  },
  {
    yek: "update_delete_workflow",
    xmlYek: "update_delete_workflow",
    api: "",
    description: "",
  },
  {
    yek: "action_point_status",
    xmlYek: "action_point_status",
    api: "",
    description: "",
  },
  {
    yek: "save_covernote_files",
    xmlYek: "save_covernote_files",
    api: "",
    description: "",
  },
  {
    yek: "get_user_by_office_id",
    xmlYek: "get_user_by_office_id",
    api: "",
    description: "",
  },
  {
    yek: "Department_User_Xml_Data",
    xmlYek: "Department_User_Xml_Data",
    api: "",
    description: "",
  },
  {
    yek: "Meeting_Group_Data",
    xmlYek: "Meeting_Group_Data",
    api: "",
    description: "",
  },
  {
    yek: "Meeting_Type_Data",
    xmlYek: "Meeting_Type_Data",
    api: "",
    description: "",
  },
  { yek: "Venue_Xml_Data", xmlYek: "Venue_Xml_Data", api: "", description: "" },
  {
    yek: "Facility_Manager_Xml_Data",
    xmlYek: "Facility_Manager_Xml_Data",
    api: "",
    description: "",
  },
  {
    yek: "Meeting_Schedule_Data",
    xmlYek: "Meeting_Schedule_Data",
    api: "",
    description: "",
  },
  {
    yek: "Schedule_Meeting_Save_Update_Delete",
    xmlYek: "Schedule_Meeting_Save_Update_Delete",
    api: "",
    description: "",
  },
  {
    yek: "agenda_Status_Details",
    xmlYek: "agenda_Status_Details",
    api: "",
    description: "",
  },
  { yek: "Meeting_Report", xmlYek: "Meeting_Report", api: "", description: "" },
  {
    yek: "GetConsolidatedReport",
    xmlYek: "GetConsolidatedReport",
    api: "api/servicep/web/9e9ead45540e/ctrl/T3gMnayuEp3/internal/party/hRusW/request/2021dEc24/api/getconsolidatedreport",
    description: "",
  },
  {
    yek: "Chairman_Secretary_Member_And_Invitees_Data",
    xmlYek: "Chairman_Secretary_Member_And_Invitees_Data",
    api: "",
    description: "",
  },
  {
    yek: "get_act_master_details",
    xmlYek: "get_act_master_details",
    api: "",
    description: "",
  },
  {
    yek: "MeetingAgendaOperations",
    xmlYek: "MeetingAgendaOperations",
    api: "",
    description: "",
  },
  {
    yek: "Save_Circular_Resolution_Details",
    xmlYek: "Save_Circular_Resolution_Details",
    api: "",
    description: "",
  },
  {
    yek: "Get_Circular_Resolution_Details",
    xmlYek: "Get_Circular_Resolution_Details",
    api: "",
    description: "",
  },
  {
    yek: "Get_Circular_Resolution_AgendaStatus",
    xmlYek: "Get_Circular_Resolution_AgendaStatus",
    api: "",
    description: "",
  },
  {
    yek: "usp_WithdrewInternalNote",
    xmlYek: "usp_WithdrewInternalNote",
    api: "",
    description: "",
  },
  {
    yek: "Action_Response_By_ClosureDetails",
    xmlYek: "Action_Response_By_ClosureDetails",
    api: "",
    description: "",
  },
  {
    yek: "InteranlNoteStatusComboData",
    xmlYek: "InteranlNoteStatusComboData",
    api: "",
    description: "",
  },
  {
    yek: "Get_Frequency_Details",
    xmlYek: "Get_Frequency_Details",
    api: "",
    description: "",
  },
  {
    yek: "Save_Calendar_Submission",
    xmlYek: "Save_Calendar_Submission",
    api: "",
    description: "",
  },
  {
    yek: "Get_Calendar_Submission_Details",
    xmlYek: "Get_Calendar_Submission_Details",
    api: "",
    description: "",
  },
  {
    yek: "GetDashboardDetails",
    xmlYek: "GetDashboardDetails",
    api: "",
    description: "",
  },
  {
    yek: "Get_Department_Calendar_Details",
    xmlYek: "Get_Department_Calendar_Details",
    api: "",
    description: "",
  },
  {
    yek: "save_Department_Calendar_Submission_Details",
    xmlYek: "save_Department_Calendar_Submission_Details",
    api: "",
    description: "",
  },
  {
    yek: "Get_Userwise_DepartmentDetails_Xml",
    xmlYek: "Get_Userwise_DepartmentDetails_Xml",
    api: "",
    description: "",
  },
  {
    yek: "GetInternalNoteSearchDetails",
    xmlYek: "GetInternalNoteSearchDetails",
    api: "",
    description: "",
  },
  {
    yek: "Get_Circular_Resolution_DecisionStatus",
    xmlYek: "Get_Circular_Resolution_DecisionStatus",
    api: "",
    description: "",
  },
  {
    yek: "GetDepartmentWiseUserDetails",
    xmlYek: "GetDepartmentWiseUserDetails",
    api: "",
    description: "",
  },
  {
    yek: "GetDepartmentAndHeadDetails",
    xmlYek: "GetDepartmentAndHeadDetails",
    api: "",
    description: "",
  },
  {
    yek: "usp_DepartmentHeadCheck",
    xmlYek: "usp_DepartmentHeadCheck",
    api: "",
    description: "",
  },
  {
    yek: "getComplianceStatus",
    xmlYek: "getComplianceStatus",
    api: "",
    description: "",
  },
  {
    yek: "ExcelCountChecking",
    xmlYek: "ExcelCountChecking",
    api: "",
    description: "",
  },
  {
    yek: "save_agenda_master_details",
    xmlYek: "save_agenda_master_details",
    api: "",
    description: "",
  },
  {
    yek: "get_agenda_details",
    xmlYek: "get_agenda_details",
    api: "",
    description: "",
  },
  {
    yek: "get_manageAgenda",
    xmlYek: "get_manageAgenda",
    api: "",
    description: "",
  },
  {
    yek: "User_Role_Details",
    xmlYek: "User_Role_Details",
    api: "",
    description: "",
  },
  {
    yek: "save_update_delete_user_role",
    xmlYek: "save_update_delete_user_role",
    api: "",
    description: "",
  },
  {
    yek: "User_Registration_Details",
    xmlYek: "User_Registration_Details",
    api: "",
    description: "",
  },
  {
    yek: "User_Role_Combo_Data",
    xmlYek: "User_Role_Combo_Data",
    api: "",
    description: "",
  },
  {
    yek: "Employee_Combo_Data",
    xmlYek: "Employee_Combo_Data",
    api: "",
    description: "",
  },
  {
    yek: "save_update_delete_new_user",
    xmlYek: "save_update_delete_new_user",
    api: "",
    description: "",
  },
  {
    yek: "get_manageagenda_packet",
    xmlYek: "get_manageagenda_packet",
    api: "",
    description: "",
  },
  {
    yek: "Get_Meeting_Agneda_Status",
    xmlYek: "Get_Meeting_Agneda_Status",
    api: "",
    description: "",
  },
  {
    yek: "get_user_data_by_Username",
    xmlYek: "get_user_data_by_Username",
    api: "",
    description: "",
  },
  { yek: "save_pwd", xmlYek: "save_pwd", api: "", description: "" },
  { yek: "Generate_Otp", xmlYek: "Generate_Otp", api: "", description: "" },
  {
    yek: "Check_UserDuplicate",
    xmlYek: "Check_UserDuplicate",
    api: "",
    description: "",
  },
  { yek: "agenda_search", xmlYek: "agenda_search", api: "", description: "" },
  {
    yek: "Get_All_Department",
    xmlYek: "Get_All_Department",
    api: "",
    description: "",
  },
  {
    yek: "GetUserRightsByMenuId",
    xmlYek: "GetUserRightsByMenuId",
    api: "",
    description: "",
  },
  {
    yek: "Facily_Details_Xmldata",
    xmlYek: "Facily_Details_Xmldata",
    api: "",
    description: "",
  },
  {
    yek: "UspemployeProfPicUpdate",
    xmlYek: "UspemployeProfPicUpdate",
    api: "",
    description: "",
  },
  {
    yek: "SaveUserRoleRightAccess",
    xmlYek: "SaveUserRoleRightAccess",
    api: "",
    description: "",
  },
  {
    yek: "GetMenusByUserRights",
    xmlYek: "GetMenusByUserRights",
    api: "",
    description: "",
  },
  { yek: "invalidlogins", xmlYek: "invalidlogins", api: "", description: "" },
  { yek: "loginLogUpdate", xmlYek: "loginLogUpdate", api: "", description: "" },
  {
    yek: "CalendarSubmissionMail",
    xmlYek: "CalendarSubmissionMail",
    api: "",
    description: "",
  },
  {
    yek: "DepartmentCalendarMail",
    xmlYek: "DepartmentCalendarMail",
    api: "",
    description: "",
  },
  {
    yek: "ApprovedetailsWithNoteId",
    xmlYek: "ApprovedetailsWithNoteId",
    api: "",
    description: "",
  },
  { yek: "Query_Handler", xmlYek: "Query_Handler", api: "", description: "" },
  {
    yek: "get_ScheduledMeetingDepartments",
    xmlYek: "get_ScheduledMeetingDepartments",
    api: "",
    description: "",
  },
  { yek: "RevertAgenda", xmlYek: "RevertAgenda", api: "", description: "" },
  { yek: "CancelMeeting", xmlYek: "CancelMeeting", api: "", description: "" },
  {
    yek: "WithdrewRevertCircularResolution",
    xmlYek: "WithdrewRevertCircularResolution",
    api: "",
    description: "",
  },
];

export const serviceMapping = {
  getMapping: (yek: string): any => {
    let mapping = apiCollection.find((x) => x.yek === yek);
  },
};
